config:
  payload:
    - path: "../mock_data/vusers.csv"
      fields:
        - "name"
        - "email"
        - "password"
      skipHeader: true
      loadAll: true
      name: auth
    - path: "../mock_data/transactions.csv"
      fields:
        - "amount"
        - "date"
        - "placeId"
      skipHeader: true
  environments:
    development:
      target: http://localhost:9000/api
      phases:
        - duration: 420
          arrivalRate: 4
          name: Soak test.
  plugins:
    apdex: {}
    fake-data: {}
